### ISSUE TITLE
Resize enclave tests to support Windows CI

### ISSUE THREAD

**Issue by gupta-ak** [Microsoft/openenclave#1008]
A lot of the enclave tests create 32MB+ enclaves, which fails on Windows due to the limited EPC memory.  Only a few tests actually need MBs of memory, so we can reduce most of them to support running them on the Windows CI.

**Comment by anitagov** [comment]
Work in progress ...

**Comment by anitagov** [comment]
Got ELF enclave tests to PASS on Windows after reducing HeapPageCount and StackPageCount.

**Comment by anitagov** [comment]
The remaining ELF enclaves that are not yet enabled with Windows are:
**abortStatus** - Hitting a OE_MEMORY_LEAK on Windows due to negative tests not releasing all the memory.
**cppException**
**create-rapid**
**libc** - After reducing heap/stack sizes able to get all the libc tests to PASS excepting the following tests with clang. One test failed on gcc Linux as well. _This should be retried after Mike's optimized libc gets checked into master._

- tests/libc/math_acos (NUMERICAL)

- tests/libc/math_fenv  (NUMERICAL)

- tests/libc/math_nearbyint (NUMERICAL)

**libcxx
libcxxrt
memory**
**sealKey** - Resizing enables create_enclave to succeed but results in an Ilegal exception (needs debug)
**crypto_crls_cert_chain**
**libunwind**
**mbed**
**VectorException** 
**qeidentity** - Attestation is not supported on Windows
**report** - Attestation is not supported on Windows

**Comment by anitagov** [comment]
PR #1289 - Enabled abortStatus for Windows  after resizing ELF enclave and bypassing the result from terminate_enclave.

**Comment by anitagov** [comment]
Enabled mbed tests for Windows with my PR #1372 .
Disabled ecall_ocall for Windows as it intermittently fails with my PR #1415 .

**Comment by anitagov** [comment]
So, the current list of tests that are not enabled on Windows are:
**libc** - Enabling in progress but unable to resize for ACC VMs
**libcxx** 
**libcxxrt**
**memory**
**create-rapid**
**crypto_crls_cert_chains**
**ecall_ocall** - Was enabled and recently pulled out due to size issues on Windows
**libunwind**

**qeidentity** - Attestation is not supported on Windows
**report** - Attestation is not supported on Windows

**Comment by johnkord** [comment]
@anitagov Do you have any updates to this issue? Should we consolidate this issue with any other open issues?

**Comment by anitagov** [comment]
Closing this issue as done as the easy resizing ones were completed a while back. Remaining tests that need to be enabled on Windows are mostly 3rd party libraries which will be addressed with #1033 .
