### ISSUE TITLE
Need more or full libc test coverage in CI

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1188]
The libc tests were optimized by @mikbras (PR #782 ) and hence the full suite builds and runs very fast. 
However, only a fraction of these tests i.e. 12 of the 240 tests are being run by default with CI. Changes that break libc are not known and/or addressed immediately. One example, is the changes to support PE enclaves broke tls_align.c (Issue #1090) and the issue was filed 20 days after it occurred.

This issue will address increasing libc test coverage by default so that we catch errors and address them sooner than later as we make changes to support Windows and more.

**Comment by anitagov** [comment]
Yes, I will be trying to enable libc tests -- that is next on my plate.

**Comment by anitagov** [comment]
libc and libcxx are different. 

For enabling libc tests on Windows, they will not work on Windows automatically and the heap/stack sizes will need to reduced. But this change caused some failures on Linux as I indicated in my issue #1008 . This is a comprehensive issue and several of the tests have been enabled already. However, the ones remaining are the really tricky ones/3rd party/unsupported.

If you are working on enabling any test for Windows, let us create a new issue and also update #1008 .

Re: libcxx test enabling for Windows - The libcxx test suite was recently upgraded to work with EDL. There is an issue to optimize this. 
Building all the 5000 tests using a cross-compiler on Windows and then running them in a separate pipeline will take up a lot of resources. We are already using 2 different generators and 2 build types (4 combinations with 2 of them repeating the Linux build) and also going to be adding ninja. It seems overkill to me.

**Comment by anitagov** [comment]
Some recap: When I filed this issue, it was a request for all libc tests to be run on Linux CI as I assumed that #782 was merged to master which was optimized libc. 
John completed this with his PR #1214 on Dec 14th.
PR #782 was completed by @mikbras on Dec 19th.

So, this issue actually should have been closed.

**Comment by anitagov** [comment]
But since it hasn't. Changed the title to be generic CI.

**Comment by ionutbalutoiu** [comment]
@anitagov Thank-you very much for the detailed explanation!

With your above clarifications, I realize that the work we have been doing is trying to have some `libcxx` tests runs in the Windows CI, which I agree that it seems an overkill (the job execution time is significantly increased). We'll be leaving this on hold for now, and resume it in case it becomes a priority.

@johnkord, given the outcome of this discussion, I think that this issue is solved as part of your changes from https://github.com/Microsoft/openenclave/pull/1214. If there isn't anything else from your side, I think that we should close this issue.

**Comment by johnkord** [comment]
Agreed, let's close this!
