### ISSUE TITLE
Occasionally `Failed to extract linuxDebug.tar.gz` CI error 

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1524]
At the `windowsLinuxElfBuild` stages from CI, we have 2 steps:

* Generate Linux build on Ubuntu 18.04 / 16.04 machine
* Transfer that to Windows machine that via [stash](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#stash-stash-some-files-to-be-used-later-in-the-build) / [unstash](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#unstash-restore-files-previously-stashed) Jenkins pipeline primitive
* Run the Windows tests using the Linux build

The CI occasionally reports errors when using `unstash` and extract the archive stashed on Linux nodes:

* [Bors-trying#755](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/755/pipeline)
* [Bors-trying#744](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/744/pipeline)
* [Bors-trying#741](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/741/pipeline)

We need to see why this is happening.

**Comment by oprinmarius** [comment]
We recently added stage for GCC ELF enclaves on windows: https://github.com/Microsoft/openenclave/pull/1478

Since the compiler name wasn't part of the stash name , 
win2016LinuxElfBuild('18.04', 'gcc', 'Debug') and win2016LinuxElfBuild('18.04', 'clang-7', 'Release')  would have the same stash name creating the following problem:


Process 1 creates a stash called linux${build_type}${version}

Process 2 stashes under the same name, linux${build_type}${version}, then successfully unstashes. linux${build_type}${version} is deleted.

Process 1 attempts to unstash linux${build_type}${version}. It gets an error during unstashing because linux${build_type}${version}  was deleted by process 2.
