### ISSUE TITLE
oegdb incorrectly prints that an enclave has been loaded in simulation mode

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1708]
oegdb prints that an enclave has been loaded in simulation mode even for enclaves loaded in hardware mode. This is just a diagnostic message and should not affect debugging.
We need to make sure that the field offsets in enclave_t structure is consistent with what the debugger expects.

CC: @radhikaj

**Comment by anakrish** [comment]
@CodeMonkeyLeet  @paulcallen 

oegdb is reading values at offset 0x798 in the oe_enclave_t structure:
https://github.com/Microsoft/openenclave/blob/113a8bf22768b3152d57b31085e1cb981556ed99/debugger/pythonExtension/gdb_sgx_plugin.py#L20-L25

The correct offset is 0x788. 
sizeof(oe_enclave_t) == 0x790 and therefore the read is happening outside the oe_enclave_t structure.

**Comment by CodeMonkeyLeet** [comment]
@anakrish It looks like we index off the end of the struct definition into arbitrary memory, so there's no easy way to estimate the likely impact of this bug, correct?

**Comment by paulcallen** [comment]
The bug here is that _oe_enclave does not have a structure size at the start of the structure that the debugger can use to validate. Then, the debugger is going to have to know where important parameters are depending on the size of the structure. Then when the debugger starts up and tries to do this it will check to make sure the enclave is of a known size. If not it will barf with a really big message that hopefully the dev that made the change will see. Then they will update the debugger for that enclave size.
We will need this versioning anyway as customers will release their enclave from version x of the SDK and someone else may use SDK x+1 to debug at a future date.

**Comment by anakrish** [comment]
@CodeMonkeyLeet 

> @anakrish It looks like we index off the end of the struct definition into arbitrary memory, so there's no easy way to estimate the likely impact of this bug, correct?

Yes, it just so happens that offset 0x798 has a non zero value and the enclave is considered debuggable.
