### ISSUE TITLE
Add -Wconversion -Wpointer-arith options to linux builds

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#175]
The following essential two flags are not turned on by -Wall:

-Wconversion Warn for implicit conversions that may alter a value. 
-Wpointer-arith Warn about anything that depends on the “size of” a function type or of void.

See https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

**Comment by johnkord** [comment]
These were merged into master, but they enabled the flags for both Linux and Windows, and CL.exe doesn't know what those flags are, so this was causing the Windows build to fail!  Theses changes got past our CI gating because we've had a Windows CI outage (without knowing about it) until today.  

So the changes necessary in the source code to enable these flags are still in master, but the flags themselves were removed from master until we can re-enable them solely for Linux builds.  Refer to #1143 to see the changes that disabled these flags.

**Comment by andschwa** [comment]
This was resolved in #1135.
