### ISSUE TITLE
Enclave LIBC syscall function does not provide same guarantees as described by Linux Programmer's manual

### ISSUE THREAD

**Issue by anakrish** [microsoft/openenclave#1832]
http://man7.org/linux/man-pages/man2/syscall.2.html says:
> syscall() saves CPU registers before making the system call, restores
       the registers upon return from the system call, and stores any error
       code returned by the system call in errno(3) if an error occurs.

Additionally system calls dispatch to the platforms syscall (or equivalent instruction) that provides its own behavioral guarantees. 
E.g: https://www.felixcloutier.com/x86/syscall says:
> SYSCALL also saves RFLAGS into R11 and then masks RFLAGS using the IA32_FMASK MSR (MSR address C0000084H); specifically, the processor clears in RFLAGS every bit corresponding to a bit that is set in the IA32_FMASK MSR.

It is not clear if the syscall hook function in OE libc provides the same guarantees:
https://github.com/microsoft/openenclave/blob/eac946aaec2a71e7d48283bd025ee84aed10f9f5/libc/sgx/syscalls.c#L226-L251

**Comment by anakrish** [comment]
CC: @CodeMonkeyLeet @paulcallen @dthaler

**Comment by dthaler** [comment]
Do we really want to expose the raw syscall() publically to apps?  If not, it doesn't matter what the behavior is as long as the public calls hide it.

**Comment by anakrish** [comment]
> Do we really want to expose the raw syscall() publically to apps? 

GLIBC and MUSL do. But we could choose to not provide it.

> If not, it doesn't matter what the behavior is as long as the public calls hide it.

There is more to it than just public calls. libc library implementations (e.g MUSL) internally use the syscall function to call into kernel syscall function implementation, and rely on the guarantees provided by the syscall. If the syscall function's semantics are not preserved, then enclave's libc may not behave as expected.

**Comment by anitagov** [comment]
Capturing some of the discussion that I had with Mike on 5/30. 
Since the oe_syscall is not actually invoking the instruction syscall for Intel X64 systems, here are some observations:
1) This actually does the oe_ocall to the host which preserves all the registers when the host is Linux. So, we are preserving more than what syscall does. 
2) However, some behaviors are not mimiced such as: (correctly pointed by Anand)
 _SYSCALL also saves RFLAGS into R11 and then masks RFLAGS using the IA32_FMASK MSR (MSR address C0000084H); specifically, the processor clears in RFLAGS every bit corresponding to a bit that is set in the IA32_FMASK MSR._
Here is a table that lists the common RFLAGS which we need to watch out for. There can be adverse affects or different behavior if any of the bits are different.
https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-cus-d10-1cb505379b13fa05b82070226dc9b785/views/imgo
3) The Linux manpage for syscall() does not go into the details but has a large section on architecture-specific requirements. Specific handling may need to be done on certain 32-bit architectures. We don't support 32-bit on Intel but we do on ARM TrustZone.  Here are a few relevant lines from the man page.
However, when using syscall() to make a system call,
       the caller might need to handle architecture-dependent details; this
       requirement is most commonly encountered on certain 32-bit
       architectures.

       For example, on the ARM architecture Embedded ABI (EABI), a 64-bit
       value (e.g., long long) must be aligned to an even register pair.
       Thus, using syscall() instead of the wrapper provided by glibc, the
       readahead() system call would be invoked as follows on the ARM
       architecture with the EABI in little endian mode:

           syscall(SYS_readahead, fd, 0,
                   (unsigned int) (offset & 0xFFFFFFFF),
                   (unsigned int) (offset >> 32),
                   count);

       Since the offset argument is 64 bits, and the first argument (fd) is
       passed in r0, the caller must manually split and align the 64-bit
       value so that it is passed in the r2/r3 register pair.  That means
       inserting a dummy value into r1 (the second argument of 0).  Care
       also must be taken so that the split follows endian conventions
       (according to the C ABI for the platform).

4) Mike is saving/restoring more registers than the syscall instruction. His modifications to the vectored exception hander (./include/openenclave/internal/context.inc) is in the feature.exec branch.
This is done to save registers:
    pushfq
    pushq %rbp
    pushq %rsp
    pushq %rbx
    pushq %rcx
    pushq %rdx
    pushq %rsi
    pushq %rdi
    pushq %r8
    pushq %r9
    pushq %r10
    pushq %r11
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15

And to restore:
    pushq %rdx
    movq %rsp, %rdx
    addq $15, %rdx
    andq $0xFFFFFFFFFFFFFFF0, %rdx
    fxrstor (%rdx)
    popq %rdx
    addq $512 + 16, %rsp
    ldmxcsr (%rsp)
    addq $16, %rsp
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %r11
    popq %r10
    popq %r9
    popq %r8
    popq %rdi
    popq %rsi
    popq %rdx
    popq %rcx
    popq %rbx
    popq %rsp
    popq %rbp
    popfq
 


    subq $16, %rsp

    stmxcsr (%rsp)


 


    subq $512 + 16, %rsp

    pushq %rdx

    movq %rsp, %rdx

    addq $15, %rdx

    andq $0xFFFFFFFFFFFFFFF0, %rdx

    fxsave (%rdx)

**Comment by yakman2020** [comment]
syscall in the enclave is just a function call, not a process boundary crossing.

**Comment by yakman2020** [comment]
Raise with mike or li if you have additional concerns.
