### ISSUE TITLE
Test samples from their installed location

### ISSUE THREAD

**Issue by mikbras** [Microsoft/openenclave#748]
The original build system tested the samples in their installed location, that is Open Enclave was installed itself under the build output directory and the samples were run there. When **cmake** was introduced last year, the sample build scripts were reworked to reference includes, libraries, and commands under the source tree. This methodology is fragile and does not test whether the samples would actually build for the end-user.

Unfortunately, to get all this goodness, the old build system did a complete build and install. A compromise might be to use the **DESTDIR** variable so the samples could be installed under the output build directory as follows.

```
make DESTDIR=<output build directory>
```

**Comment by andschwa** [comment]
This proved to be quite difficult. The `DESTDIR` option only kind of works. It correctly pointed a CMake installation to another directory, but it failed to update the `CMAKE_INSTALL_PREFIX` which meant that the installed CMake packages could not be used. I had to instead implement logic to update the cache variable before doing the test install for the samples, which is unfortunate, but it only happens if the tests are run.

**Comment by andschwa** [comment]
The linked PR should close this issue, though it's only the first step as it fixes one sample, with @aserdean to follow up with conversions of the rest of the samples.

**Comment by andschwa** [comment]
Actually, I believe I've just managed to make the CMake package relocatable, so my hack went away 😄

**Comment by andschwa** [comment]
Closed via #1472.
