### ISSUE TITLE
should oe_is_{within|outside}_enclave be internal?

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#846]
Now that we have EDL code generation, the main use cases for these APIs are from generated code, which would make them just “internal”.

Is there any reason to recommend them to be called directly by enclave code that normal developers write?

Currently there are 0 samples that use oe_is_outside_enclave,
and oe_is_within_enclave is used by the attestation samples for no reason that I can figure out from looking through the code.

Can we declare them internal and make the attestation samples not call them except from within the generated code?

**Comment by ihaller** [comment]
#899 needs to change first to go from deprecated to fully removed. Also the [user_check] attribute in EDL needs to be documented as unsupported in that case. Nested pointers as arguments would also be completely unsupported with such a change (since the user would not be able to perform relevant checks).

**Comment by lilyfang** [comment]
The APIs are currently used by OE SDK application.
