### ISSUE TITLE
Clarify/change "executable" in add_enclave_executable

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#891]
The `add_enclave_executable` CMake helper function uses `add_executable` to create an enclave binary, which is then signed and written to `<target_name>.signed.so`.

In tests which don't use this helper function, a plain `add_executable` call is used.

In general, this confuses me as the file extension after signing is `.so` which seems to say it is a shared library also before signing, so why isn't `add_library(.. SHARED)` used?

**Comment by andschwa** [comment]
@letmaik Yeah I had similar thoughts when I was looking at this. What's more, `add_enclave_executable` actually generates both a (useless) executable _and_ a shared library. It's weird.

**Comment by andschwa** [comment]
@radhikaj My proposed API would look like this.

# Existing use

## With Signing
This is fairly bad because it wraps `add_executable`. And inside, it only uses `add_executable` because (presumably) they did not want the `lib` prefix or `.so` suffix. This "executable" is not an executable, but it's generated as one and left-around.

```
include(add_enclave_executable)
add_enclave_executable(no_debug_enc sign.conf
    enc.c
    props.c)
```

## Without Signing
Hilarious because it doesn't use the function!
```
include(add_enclave_executable)
add_executable(VectorException_enc
    enc.c
    sigill_handling.c
    init.cpp
    )

target_link_libraries(VectorException_enc oeenclave)
```

Same reason for `add_executable`, they used it just for its naming conventions.

# Proposal

## With signing
```
add_library(no_debug_enc SHARED enc.c props.c)
target_make_enclave(no_debug_enc CONF sign.conf)
```

I think that wrapping `add_executable`/`add_library` is a terrible thing to do in CMake, as it creates "magic" and confuses people. I think, instead, that creating an enclave should be two steps:

1. Create the shared library (like normal, using CMake's `add_library`).
2. Create the enclave (using our function)

Then our CMake `function make_enclave()` should use [cmake_parse_arguments](https://cmake.org/cmake/help/latest/command/cmake_parse_arguments.html#command:cmake_parse_arguments) to accept the one value parameters `TARGET` and `CONF`, where target is the library and conf is the signing configuration.

We should use `parse_arguments` because it gives us the flexibility to add options later without rewriting all uses of the function (such as: accepting a key file instead of generating one), plus it's cleaner when using the function.

To refer to the library's file name (like for `oesign`) the generator expression `$<TARGET_FILE:foo>` works. Thus, we do not need to overwrite the library's `PREFIX` or `SUFFIX`.

## Without Signing

In this case, all these should just be switched to `add_library(VectorException_enc SHARED enc.c sigill_handling.c init.cpp)`. Since this changes the name, we need to update `add_enclave_test()` to use `$<TARGET_FILE:${ENC_FILE}>` (this means fixing the embedded `add_test` to use the `COMMAND` style so generator expressions are supported.

**Comment by radhikaj** [comment]
@mikbras @anakrish 

When I build the enclave as an SHARED library, rather than an executable, the tests still pass. 
@anakrish suggested dumping out the linker commands to verify PIE was being used while generating the .so. The linker command does show that -PIE is being used by the linker.

Here is the verbose output of make.
@mikbras could you please comment on whether the enclaves should be added as executables or sos.

[100%] Building C object tests/props/enc/CMakeFiles/props_enc.dir/props_t.c.o
cd /home/user/oe/build/tests/props/enc && /usr/bin/clang-7  -DOE_BUILD_ENCLAVE -Dprops_enc_EXPORTS -I/home/user/oe/build/tests/props/enc -I/home/user/oe/build/output/include/openenclave -I/home/user/oe/build/output/include/openenclave/libc -I/home/user/oe/include  -g -fPIC   -mllvm -x86-speculative-load-hardening -Wno-error=unused-command-line-argument -Wall -Werror -fno-strict-aliasing -mxsave -fno-builtin-malloc -fno-builtin-calloc -m64 -fPIC -nostdinc -fno-stack-protector -fvisibility=hidden -o CMakeFiles/props_enc.dir/props_t.c.o   -c /home/user/oe/build/tests/props/enc/props_t.c
[100%] Linking C shared library libprops_enc.so
cd /home/user/oe/build/tests/props/enc && /usr/bin/cmake -E cmake_link_script CMakeFiles/props_enc.dir/link.txt --verbose=1
/usr/bin/clang-7  -fPIC -g  -shared -Wl,-soname,libprops_enc.so -o libprops_enc.so CMakeFiles/props_enc.dir/enc.c.o CMakeFiles/props_enc.dir/props.c.o CMakeFiles/props_enc.dir/props_t.c.o ../../../output/lib/openenclave/enclave/liboeenclave.a ../../../output/lib/openenclave/enclave/libmbedtls.a ../../../output/lib/openenclave/enclave/libmbedx509.a ../../../output/lib/openenclave/enclave/libmbedcrypto.a ../../../output/lib/openenclave/enclave/liboelibc.a ../../../output/lib/openenclave/enclave/liboecore.a ../../../output/lib/openenclave/enclave/liboelibc.a ../../../output/lib/openenclave/enclave/liboecore.a -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie
make[2]: Leaving directory '/home/user/oe/build'
[100%] Built target props_enc
make -f tests/props/enc/CMakeFiles/props_enc-signed.dir/build.make tests/props/enc/CMakeFiles/props_enc-signed.dir/depend
make[2]: Entering directory '/home/user/oe/build'
cd /home/user/oe/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/user/oe /home/user/oe/tests/props/enc /home/user/oe/build /home/user/oe/build/tests/props/enc /home/user/oe/build/tests/props/enc/CMakeFiles/props_enc-signed.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/user/oe/build'
make -f tests/props/enc/CMakeFiles/props_enc-signed.dir/build.make tests/props/enc/CMakeFiles/props_enc-signed.dir/build
make[2]: Entering directory '/home/user/oe/build'
[100%] Generating props_enc-private.pem
cd /home/user/oe/build/tests/props/enc && openssl genrsa -out props_enc-private.pem -3 3072
Generating RSA private key, 3072 bit long modulus
...............................++
................................................................................................................................................................................................++
e is 3 (0x3)
[100%] Generating props_enc.signed.so
cd /home/user/oe/tests/props/enc && /home/user/oe/build/output/bin/oesign /home/user/oe/build/tests/props/enc/libprops_enc.so sign.conf /home/user/oe/build/tests/props/enc/props_enc-private.pem
Created /home/user/oe/build/tests/props/enc/libprops_enc.signed.so

**Comment by radhikaj** [comment]
One more input into this discussion.
@anakrish  printed out verbose output from the linker(by copying the linker command from verbose make and adding a -v before -fPIC). It appears that -PIE  and -shared are both accepted by the linker.
 /usr/bin/clang-7 -v -fPIC -g  -shared -Wl,-soname,libprops_enc_unsigned.so -o libprops_enc_unsigned.so CMakeFiles/props_enc_unsigned.dir/enc.c.o CMakeFiles/props_enc_unsigned.dir/props.c.o CMakeFiles/props_enc_unsigned.dir/props_t.c.o ../../../output/lib/openenclave/enclave/liboeenclave.a ../../../output/lib/openenclave/enclave/libmbedtls.a ../../../output/lib/openenclave/enclave/libmbedx509.a ../../../output/lib/openenclave/enclave/libmbedcrypto.a ../../../output/lib/openenclave/enclave/liboelibc.a ../../../output/lib/openenclave/enclave/liboecore.a ../../../output/lib/openenclave/enclave/liboelibc.a ../../../output/lib/openenclave/enclave/liboecore.a -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie

The output shows that -PIE and -shared were both accepted by the linker
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -shared -o libprops_enc_unsigned.so -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../.. -L/usr/lib/llvm-7/bin/../lib -L/lib -L/usr/lib -soname libprops_enc_unsigned.so CMakeFiles/props_enc_unsigned.dir/enc.c.o CMakeFiles/props_enc_unsigned.dir/props.c.o CMakeFiles/props_enc_unsigned.dir/props_t.c.o ../../../output/lib/openenclave/enclave/liboeenclave.a ../../../output/lib/openenclave/enclave/libmbedtls.a ../../../output/lib/openenclave/enclave/libmbedx509.a ../../../output/lib/openenclave/enclave/libmbedcrypto.a ../../../output/lib/openenclave/enclave/liboelibc.a ../../../output/lib/openenclave/enclave/liboecore.a ../../../output/lib/openenclave/enclave/liboelibc.a ../../../output/lib/openenclave/enclave/liboecore.a --no-undefined -Bstatic -Bsymbolic --export-dynamic -pie

**Comment by radhikaj** [comment]
Here us another input. The .so is a Position Independent Executable
 hardening-check libprops_enc.so
libprops_enc.so:
 Position Independent Executable: yes
 Stack protected: no, not found!
 Fortify Source functions: unknown, no protectable libc functions used
 Read-only relocations: yes
 Immediate binding: no, not found!

**Comment by andschwa** [comment]
@radhikaj, @anakrish, and I had a chat. In order to later support ELF enclaves on Windows, we're changing direction a bit here. We're proposing:

```
add_enclave(<target> [CONF [conf-file]] [LIBRARY] <files>)
```
We will use `cmake_parse_arguments` so that we can add `LIBRARY` as a boolean option later to support (libraries loaded into enclaves).

`CONF` will be an optional argument that, when present, triggers signing of the enclave.

The function itself will do:

```
if (NOT LIBRARY)
  add_executable(<target> <files>)
  # explicitly note/set that `-fPIE` must be used
  # set suffix name of executable to be `.so` to match Intel's naming scheme
else ()
  # TODO lots to support enclave libraries (this whole if/else/endif won't be in the first fix to this function)
endif ()

if (CONF)
... sign the executable ...
endif ()
```

Since `CONF` will be optional, tests can simply not opt-in to signing. We _do_ want to wrap `add_executable` so that we can maintain control over properties set for enclaves.

This function will eventually be exported into our CMake package.

@anakrish @radhikaj @mikbras was there anything else I missed?

**Comment by andschwa** [comment]
Update from @anakrish: We will _not_ be appending `.so` to the enclave names, as it confuses people!

**Comment by radhikaj** [comment]
This has been addressed by PR: https://github.com/Microsoft/openenclave/pull/1199
#1199

**Comment by anitagov** [comment]
@radhikaj @andschwa and all - Very nice!!!

**Comment by andschwa** [comment]
The rest of the work is tracked in #1221. I'll close this now!
