### ISSUE TITLE
Inconsistent usage of single underscores.

### ISSUE THREAD

**Issue by mikbras** [Microsoft/openenclave#948]
In several places, global symbols are prefixed with "_oe_". The single underscore is reserved for local definitions (static, file-scope definitions). These usages should simply use the "oe_" prefix. Further, local symbols should not be prefixed with "_oe_" (rather the prefix should be dropped).

**Comment by anitagov** [comment]
Here is confirmation from the POSIX standard, Section 7.1.3  - http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf
**7.1.3 Reserved identifiers of the C Standard:**

- All identifiers that begin with an underscore and either an uppercase letter or another
underscore are always reserved for any use. 

- All identifiers that begin with an underscore are always reserved for use as identifiers
with file scope in both the ordinary and tag name spaces.
--------------
**So, in shor**t:  You cannot define any identifiers in global scope whose names begin with an underscore, because these may conflict with hidden (private) library definitions.
