### ISSUE TITLE
Add tests for unsigned char, unsigned short, unsigned int, unsigned long and unsigned long long

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#978]
We have tests only for the default (signed) versions of these types.
To minimize development conflicts, these tests need to be added after the existing oeedger8r test has been made to work on windows.

**Comment by anakrish** [comment]
@paulcallen @gupta-ak

**Comment by anitagov** [comment]
Work in progress...

**Comment by anitagov** [comment]
@anakrish - I already completed this last Wednesday and wanted to issue the PR today after some more testing. I see that VVDN completed unsigned long. Will merge and add my changes for the remaining types. 
The Assignee should be changed if it is reassigned to someone else in order to avoid duplicate work. I also believe that a Work-in-progress field is needed to avoid reassignment of tasks in progress.

**Comment by vishnumohan1991** [comment]
@anakrish  Add test for missing data type `unsigned long long`.

**Comment by anitagov** [comment]
Closing this as this has been completed with the PRs #1120 , #1147 and #1122
